import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >


        <nav className="w-full bg-red-200 text-black p-5 rounded-lg shadow-lg flex justify-between items-center">

          {/* LEFT SIDE: Website Title */}
          <h1 className="text-xl font-bold">My Demo Website</h1>

          {/* RIGHT SIDE: Menu */}
          <div className="flex gap-6">
            <Link href="/" className="hover:text-red-600 font-medium">
              Home
            </Link>
            <Link href="/about" className="hover:text-red-600 font-medium">
              About
            </Link>
            <Link href="/contact" className="hover:text-red-600 font-medium">
              Contact
            </Link>
          </div>

        </nav>



        {children}
      </body>
    </html>
  );
}
