import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full bg-gradient-to-r from-blue-600 to-blue-800 text-white px-8 py-4 shadow-xl">
          <div className="max-w-7xl mx-auto flex items-center justify-between">

            {/* Logo */}
            <div className="text-2xl font-bold tracking-wide">
              DHANSETU <span className="text-yellow-300">WEALTH</span>
            </div>

            {/* Links */}
            <div className="flex space-x-8 text-lg">
              <Link href="/home" className="hover:text-yellow-300 transition">Home</Link>
              <Link href="/mutualfund" className="hover:text-yellow-300 transition">Mutual Fund</Link>
              <Link href="/insurace" className="hover:text-yellow-300 transition">Insurance</Link>
              <Link href="/about" className="hover:text-yellow-300 transition">About</Link>
              <Link href="/contact" className="hover:text-yellow-300 transition">Contact</Link>
            </div>

            {/* CTA Button */}
            <Link
              href="/contact"
              className="bg-yellow-400 text-black px-5 py-2 rounded-lg font-medium hover:bg-yellow-300 transition shadow-md"
            >
              Get Started
            </Link>

          </div>
        </nav>



        {children}
      </body>
    </html>
  );
}
